package com.jvt.devthread.employee.Activity.Common;

import androidx.fragment.app.Fragment;

public class Common {
    public static String IMAGE_REF = "REFRENCE";
    public static String IMAGE_REF_TEST = "REFRENCE";
    public static String ORDER_REF = "ORDER";
    //public static UserInfoModel currentUser;
    public static final String USER_REFERENCES="Users";
    public static String FEATURE_REFERENCES="Feature";
    public static String USER_UID ="UID" ;
    public static String QUERY_ID ="ID" ;
    public static String QUERY_EMAIL ="Email" ;
    public static String QUERY_TIME ="TIME" ;
    public static String QUERY_SUBJECT ="subject" ;
    public static String QUERY_QUESTION ="question" ;
    public static String QUERY_ANSWER ="answer" ;
    public static String DEVELOPER_ID ="id" ;
    public static String DEVELOPER_DESIGNATION ="id" ;
    public static String DEVELOPER_EXPERIENCE ="id" ;
    public static String DEVELOPER_PROJECTS ="id" ;
    public static String DEVELOPER_NAME ="id" ;
    public static String DEVELOPER_REFERENCE ="reference" ;
    public static final int DEFAULT_COLUMN_COUNT = 0;
    public static final int FULL_WIDTH_COLUMN =1 ;
    public static final String DEVELOPERS_PROFILE="DevelopersProfile";
    public static Fragment activeFragment;
    public static String usersUid;
    public static String orderId;

    public static String orderStatus;
    public static String userName;
    public static String userEmail;
    public static String itemSelected;
    public static Long ordTotalVal;
    public static Long ordPaidVal;
    public static Long ordDueVal;
    public static String paymentType;
    public static String domainName;
    public static String featureName;
    public static String productName;
    public static String osName;
    public static String techName;
    public static String deliveryName;
    public static String serviceName;
    public static String selectedUserId;
    public static String selectedUserEmail;
    public static String orderTime;
    public static String ticketId;
    public static String ticketStatus;
    public static String demoId;
    public static String userUid;
    public static String empName;
    public static String workType;
    public static String pType;
    public static String pId;
    public static String pPlatform;
    public static String dTag;
    public static String uFeateures;
    public static String name;
    public static String empId;
    public static String empEmail;
    public static String empPhone;
    public static String adminEmail;
    public static String empAddress;
}
